version: "3.9"
services:
  mc_web_console:
    build: .
    image: mc_web_console
    ports: 
      - "5003:5003"
    volumes:
      - .:/usr/src/app
    networkd:
      mc-block-net:
        ipv4_address: 172.90.0.40

networks:
  mc-block-net:
    external: true